### ISSUE TITLE
App no longer works after restarting the computer

### ISSUE THREAD

**Issue by XiaoTDM** [ModernFlyouts-Community/ModernFlyouts#1227]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 22H2

### OS build

22621.2134

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

When I first installed ModernFlyouts and launched, everything worked fine with the app, but when the device was restarted, or even after hibernating and waking up, the app no longer worked, there was no tray icon in the taskbar, and nothing happened when I opened the app, and in Task Manager I see that the app process crashed after a few seconds. Neither repairing nor resetting the app in Settings works.
This problem happened before and after I reinstalled the system, but before reinstalling, when I clicked "Settings" in the app jump list, it would show "The item "Settings" pointed to by the shortcut had been changed or moved, and the shortcut did not work properly“.

### ✔️ Expected Behavior

The app works correctly.

### ❌ Actual Behavior

The app doesn't start at all.

### Additional Context

(The following sections may be Chinese.)

Faulting application name: Bro_x64.exe，version: 10.0.15063.0 time stamp: 0x782fe8f8
Faulting module name: KERNELBASE.dll，版本: 10.0.22621.2134，timestamp: 0xc42b59fb
Exception code: 0xe0434352
Fault offset: 0x0000000000064c3c
Faulting process ID: 0x0x47AC
Faulting application start time: 0x0x1D9DBE01563797E
Faulting application path: C:\Program Files\WindowsApps\32669SamG.ModernFlyouts_0.9.0.0_x64__pcy8vm99wrpcg\Bro_x64.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: c1ea85c6-49fc-4a2f-a639-ceb41fa73989
Faulting package full name: 32669SamG.ModernFlyouts_0.9.0.0_x64__pcy8vm99wrpcg
Faulting package-relative application ID: App

Application: Bro_x64.exe
CoreCLR Version: 5.0.120.57516
.NET Version: 5.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException: 调用线程无法访问此对象，因为另一个线程拥有该对象。
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.Freezable.System.Windows.ISealable.get_IsSealed()
   at System.Windows.StyleHelper.SealIfSealable(Object value)
   at System.Windows.ResourceDictionary.SealValues()
   at System.Windows.ResourceDictionary.AddOwner(DispatcherObject owner)
   at System.Windows.ResourceDictionary.PropagateParentOwners(ResourceDictionary mergedDictionary)
   at System.Windows.ResourceDictionary.OnMergedDictionariesChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.SetItem(Int32 index, T item)
   at System.Windows.ResourceDictionaryCollection.SetItem(Int32 index, ResourceDictionary item)
   at System.Collections.ObjectModel.Collection`1.set_Item(Int32 index, T value)
   at ModernWpf.MergedDictionariesHelper.InsertOrReplace(Collection`1 mergedDictionaries, Int32 index, ResourceDictionary item)
   at ModernWpf.ThemeResources.ApplyApplicationTheme(ApplicationTheme theme)
   at ModernWpf.ThemeManager.ApplyApplicationTheme()
   at ModernWpf.ThemeManager.OnActualApplicationThemeChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyPropertyKey key, Object value)
   at ModernWpf.ThemeManager.set_ActualApplicationTheme(ApplicationTheme value)
   at ModernWpf.ThemeManager.UpdateActualApplicationTheme()
   at ModernWpf.ThemeManager.OnSystemThemeChanged(Object sender, EventArgs e)
   at ModernWpf.ColorsHelper.UpdateColorValues()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at ModernFlyouts.Program.<>c.<Main>b__2_0()
   at ModernFlyouts.AppLifecycle.AppLifecycleManager.StartApplication(String[] args, Action action)
   at ModernFlyouts.Program.Main(String[] args)

故障存储段 2212739313390380308，类型 5
事件名称: MoAppCrash
响应: 不可用
Cab ID: 0__

**Comment by manstheram** [comment]
Try the beta build in the Releases tab of this repository.

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
